######################################################################
# Automatically generated by qmake (3.0) ?? 12? 30 15:25:31 2016
######################################################################

TEMPLATE = lib
CONFIG += static
TARGET = aggiert
INCLUDEPATH += .
VERSION = 0.0.1

# Input
HEADERS += aggie.h aggiert.h
SOURCES += aggiert.cpp
